char *INDEX_HTML[] = {
    "<html><head>",
    "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"/>",
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=us-ascii\">",
    "<title>XeLL Reloaded - HexaMods</title>",
    "<link href='https://fonts.googleapis.com/css2?family=VT323&display=swap' rel='stylesheet' type='text/css'>",
    "<link href='https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&display=swap' rel='stylesheet' type='text/css'>",

    "<style type=\"text/css\">",
    "body {",
    "    background-color: #000;",
    "    color: #0FF;",
    "    font-family: 'VT323', monospace;",
    "    text-align: center;",
    "    margin: 0;",
    "    padding: 20px;",
    "}",
    "h1, h2 {",
    "    color: #0FF;",
    "    font-family: 'Rajdhani', sans-serif;",
    "    text-shadow: 0px 0px 10px #0FF;",
    "}",
    ".container {",
    "    margin: auto;",
    "    max-width: 800px;",
    "    padding-bottom: 20px;",
    "}",
    ".box {",
    "    background-color: #111;",
    "    border: 2px solid #0FF;",
    "    padding: 15px;",
    "    margin: 15px auto;",
    "    width: 90%;",
    "    box-shadow: 0px 0px 15px #0FF;",
    "    border-radius: 8px;",
    "    transition: all 0.3s ease-in-out;",
    "}",
    ".box:hover {",
    "    transform: scale(1.03);",
    "    box-shadow: 0px 0px 25px #0FF;",
    "}",
    "button {",
    "    background-color: #000;",
    "    border: 2px solid #0FF;",
    "    color: #0FF;",
    "    padding: 10px 20px;",
    "    font-size: 16px;",
    "    cursor: pointer;",
    "    box-shadow: 0px 0px 10px #0FF;",
    "    border-radius: 5px;",
    "    transition: all 0.3s ease-in-out;",
    "    margin: 5px;",
    "    width: 200px;",
    "    display: inline-block;",
    "}",
    "button:hover {",
    "    background-color: #0FF;",
    "    color: #000;",
    "    transform: scale(1.05);",
    "}",
    "a {",
    "    color: #0FF;",
    "    text-decoration: none;",
    "    font-weight: bold;",
    "}",
    "a:hover {",
    "    text-shadow: 0px 0px 10px #0FF;",
    "}",
    "@media (max-width: 600px) {",
    "    .box { width: 95%; }",
    "    button { width: 100%; }",
    "}",
    "</style>",

    "<script>",
"function updateUptime() {",
"    fetch('/uptime').then(response => response.text()).then(data => {",
"        document.getElementById('uptime').innerText = data;",
"    });",
"    setTimeout(updateUptime, 1000);",
"}",
"window.onload = updateUptime;",
"</script>",

    "</head><body>",
    "<div class=\"container\">",
    "<h1>XeLL Reloaded - HexaMods</h1>",
    "<p>Customized by HexaMods Team</p>",
    "<p>Based on work by Redline99, DAYBR3AK1999, GliGli, Ced2911 &amp; Tuxuser</p>",

    "<div class=\"box\">",
    "<h2>Console Information</h2>",
    "<p><b>System Uptime:</b> <span id='uptime'>LOADING...</span></p>",
    "<p><b>Console Type:</b> <span id='console_type'>CONSOLE_TYPE</span></p>",
    "</div>",

    "<div class=\"box\">",
    "<h2>Keys</h2>",
    "<p><b>CPU Key:</b> <span id='cpu_key'>CPU_KEY</span></p>",
    "<p><b>DVD Key:</b> <span id='dvd_key'>DVD_KEY</span></p>",
    "</div>",

    "<div class=\"box\">",
    "<h2>Fuses</h2>",
    "<p><b>Fuses:</b></p>",
    "<pre id='fuse_info'>FUSE_INFO</pre>",
    "</div>",

    "<div class=\"box\">",
    "<h2>Downloads</h2>",
    "<button onclick=\"window.location.href='/FLASH'\">Download Flash</button>",
    "<button onclick=\"window.location.href='/KV'\">Download KV</button>",
    "<button onclick=\"window.location.href='/FUSE'\">Download Fuses</button>",
    "<button onclick=\"window.location.href='/LOG'\">Download XeLL Logs</button>",
    "</div>",

    "<div class=\"box\">",
    "<h2>Tools</h2>",
    "<button onclick=\"window.location.href='/LOG'\">View Log</button>",
    "<button onclick=\"window.location.href='/SHUTDOWN'\">Shutdown</button>",
    "<button onclick=\"window.location.href='/REBOOT'\">Reboot</button>",
    "</div>",

    "<div class=\"box\">",
    "<h2>Links</h2>",
    "<a href=\"https://www.hexamods.com/\" target=\"_blank\">HexaMods Official Website</a> | ",
    "<a href=\"http://www.free60.org/\" target=\"_blank\">Free60</a> | ",
    "<a href=\"http://www.libxenon.org/\" target=\"_blank\">LibXenon</a> | ",
    "<a href=\"http://www.logic-sunrise.com/\" target=\"_blank\">Logic-Sunrise</a>",
    "</div>",

    "</div>",
    "</body></html>",
};
